# Generated by Django 5.1.2 on 2024-10-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usersubscription'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersubscription',
            table='UserSubscription',
        ),
    ]
