# Generated by Django 5.1.2 on 2024-10-15 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usersubscription_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
