from __future__ import annotations
from .base import env

STRIPE_PUBLIC_KEY=env('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY=env('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET_KEY=env('STRIPE_WEBHOOK_SECRET_KEY')
STRIPE_SUCCESS_URL=env('STRIPE_SUCCESS_URL')
STRIPE_CANCEL_URL=env('STRIPE_CANCEL_URL')
STRIPE_PAYMENT_METHODS=env('STRIPE_PAYMENT_METHODS')