# Generated by Django 5.1.2 on 2024-10-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('stripe_current_period_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_subscription',
            },
        ),
    ]
